# Example configuration for merging pre-merged events using the timeframe builder
output_file: merged_timeframes2.root
max_events: 100
timeframe_duration: 200.0
bunch_crossing_period: 10.0
introduce_offsets: true
sources:
  - input_files:
      - merged_timeframes.root
    name: background
    static_number_of_events: false
    mean_event_frequency: 0.1
    use_bunch_crossing: true
    generator_status_offset: 0
    already_merged: true
  - input_files:
      - input3.root
    name: signal
    static_number_of_events: true
    static_events_per_timeframe: 1
    use_bunch_crossing: true
    generator_status_offset: 5000
