## XRootD edm4hep source configuration used in continuous integration testing

max_events: 10
timeframe_duration: 2000.0 # in ns
bunch_crossing_period: 40.0 # in ns
introduce_offsets: true
sources:
  - name: signal
    static_number_of_events: true
    static_events_per_timeframe: 1
    use_bunch_crossing: true
    generator_status_offset: 0
  - name: minbias
    static_number_of_events: false
    mean_event_frequency: 0.000083 # in GHz
    use_bunch_crossing: true
    generator_status_offset: 0
    repeat_on_eof: false
  - name: bethe_heitler
    static_number_of_events: false
    mean_event_frequency: 1.8 # in GHz # Check value
    use_bunch_crossing: true
    generator_status_offset: 7000
    repeat_on_eof: false
  - name: hadron_beamgas
    static_number_of_events: false
    mean_event_frequency: 0.0000225 # in GHz
    use_bunch_crossing: true
    attach_to_beam: true
    beam_angle: 0.025 # in rad
    beam_speed: 0.299792458 # in m/ns
    beam_spread: 0.030 # in ns
    generator_status_offset: 6000
    repeat_on_eof: false
  - name: electron_beamgas_brems
    static_number_of_events: false
    mean_event_frequency: 0.00031694 # in GHz
    use_bunch_crossing: true
    attach_to_beam: true
    beam_angle: -3.141592653589793 # in rad
    beam_speed: 0.299792458 # in m/ns
    beam_spread: 0.003 # in ns
    generator_status_offset: 3000
    repeat_on_eof: false
  - name: electron_beamgas_coulomb
    static_number_of_events: false
    mean_event_frequency: 0.00000086 # in GHz
    use_bunch_crossing: true
    attach_to_beam: true
    beam_angle: -3.141592653589793 # in rad
    beam_speed: 0.299792458 # in m/ns
    beam_spread: 0.003 # in ns
    generator_status_offset: 5000
    repeat_on_eof: false
  - name: electron_beamgas_touschek
    static_number_of_events: false
    mean_event_frequency: 0.00000055 # in GHz
    use_bunch_crossing: true
    attach_to_beam: false
    beam_angle: -3.141592653589793 # in rad
    beam_speed: 0.299792458 # in m/ns
    beam_spread: 0.003 # in ns
    generator_status_offset: 4000
    repeat_on_eof: false
  - name: electron_synchrotron
    static_number_of_events: false
    mean_event_frequency: 3.324 # in GHz
    use_bunch_crossing: true
    attach_to_beam: true
    beam_angle: -3.141592653589793 # in rad
    beam_speed: 0.299792458 # in m/ns
    beam_spread: 0.003 # in ns
    generator_status_offset: 2000
    repeat_on_eof: false
